/* JLDS — behavior layer bundle. Auto-generated by scripts/build-js-bundle.mjs — do not edit by hand. */
/* Core + every component behavior. Progressive enhancement: load after your markup (defer is fine). */

/* ---- core.js ---- */
/* JLDS behavior layer — core.
 * Defines the global `JLDS` namespace and runs registered behaviors. Pure
 * progressive enhancement: markup renders without it; this only adds behavior.
 *
 *   JLDS.register(name, fn)  — a behavior; fn(root) wires up elements under root
 *   JLDS.init(root)          — (re)run all behaviors for a subtree (e.g. after fetch)
 *
 * Behaviors are idempotent (they tag handled elements), so init is safe to
 * call repeatedly. Component files may load before or after this file.
 */
(function () {
  var J = (window.JLDS = window.JLDS || {});
  if (J._core) return; // guard against double-load
  J._core = true;

  var behaviors = (J._behaviors = J._behaviors || {});
  var ready = false;

  function run(name, root) {
    try {
      behaviors[name](root);
    } catch (e) {
      console.error("[jlds:" + name + "]", e);
    }
  }

  J.register = function (name, fn) {
    behaviors[name] = fn;
    if (ready) run(name, document);
  };

  J.init = function (root) {
    root = root || document;
    Object.keys(behaviors).forEach(function (name) {
      run(name, root);
    });
  };

  function ignite() {
    ready = true;
    J.init(document);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", ignite);
  } else {
    ignite();
  }

  // Drain behaviors that registered before this core loaded.
  var pending = J._pending || [];
  J._pending = [];
  pending.forEach(function (p) {
    J.register(p[0], p[1]);
  });
})();

/* ---- util.js ---- */
/* JLDS behavior layer — shared utilities.
 * Framework-agnostic DOM primitives reused across component behaviors (and the
 * overlay components especially). Exposed as `JLDS.util`. Load before the
 * component behavior files (the all.js bundle orders this right after core).
 */
(function () {
  var J = (window.JLDS = window.JLDS || {});
  var util = (J.util = J.util || {});

  /* Copy text to the clipboard, with a hidden-textarea fallback for old/insecure contexts. */
  util.copy = function (text) {
    function legacy() {
      var ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand("copy");
      } catch (e) {
        /* noop */
      }
      document.body.removeChild(ta);
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).catch(legacy);
    }
    legacy();
    return Promise.resolve();
  };

  /* Call handler when a pointerdown lands outside `el`. Returns a cleanup fn. */
  util.onClickOutside = function (el, handler) {
    function onDown(e) {
      if (!el.contains(e.target)) handler(e);
    }
    document.addEventListener("pointerdown", onDown, true);
    return function () {
      document.removeEventListener("pointerdown", onDown, true);
    };
  };

  /* Call handler on Escape. Returns a cleanup fn. */
  util.onEscape = function (handler) {
    function onKey(e) {
      if (e.key === "Escape") handler(e);
    }
    document.addEventListener("keydown", onKey);
    return function () {
      document.removeEventListener("keydown", onKey);
    };
  };

  /* Lock body scroll (compensating for the scrollbar). Ref-counted so nested
   * overlays don't unlock early. Returns an unlock fn. */
  var locks = 0;
  var prevOverflow = "";
  var prevPad = "";
  util.lockScroll = function () {
    if (locks === 0) {
      var sbw = window.innerWidth - document.documentElement.clientWidth;
      prevOverflow = document.body.style.overflow;
      prevPad = document.body.style.paddingRight;
      document.body.style.overflow = "hidden";
      if (sbw > 0) document.body.style.paddingRight = sbw + "px";
    }
    locks++;
    var released = false;
    return function unlock() {
      if (released) return;
      released = true;
      locks = Math.max(0, locks - 1);
      if (locks === 0) {
        document.body.style.overflow = prevOverflow;
        document.body.style.paddingRight = prevPad;
      }
    };
  };

  var FOCUSABLE =
    'a[href],button:not([disabled]),textarea:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';

  /* Trap Tab focus within `el`, focus the first focusable, and restore focus to
   * the previously-focused element on release. Returns a release fn. */
  util.focusTrap = function (el) {
    var prev = document.activeElement;
    function focusables() {
      return Array.prototype.slice.call(el.querySelectorAll(FOCUSABLE)).filter(function (n) {
        return n.offsetParent !== null || n === document.activeElement;
      });
    }
    function onKey(e) {
      if (e.key !== "Tab") return;
      var f = focusables();
      if (!f.length) {
        e.preventDefault();
        return;
      }
      var first = f[0];
      var last = f[f.length - 1];
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    }
    el.addEventListener("keydown", onKey);
    var f = focusables();
    (f[0] || el).focus();
    return function release() {
      el.removeEventListener("keydown", onKey);
      if (prev && prev.focus) prev.focus();
    };
  };
})();

/* ---- alert.js ---- */
/* JLDS behavior — Alert dismiss. Clicking .jl-alert__close removes its .jl-alert.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("alert", function (root) {
    root.querySelectorAll(".jl-alert__close").forEach(function (btn) {
      if (btn.__jlAlert) return;
      btn.__jlAlert = true;
      btn.addEventListener("click", function () {
        var el = btn.closest(".jl-alert");
        if (el) el.remove();
      });
    });
  });
})();

/* ---- banner.js ---- */
/* JLDS behavior — Banner dismiss. Clicking .jl-banner__close removes its .jl-banner.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("banner", function (root) {
    root.querySelectorAll(".jl-banner__close").forEach(function (btn) {
      if (btn.__jlBanner) return;
      btn.__jlBanner = true;
      btn.addEventListener("click", function () {
        var el = btn.closest(".jl-banner");
        if (el) el.remove();
      });
    });
  });
})();

/* ---- breadcrumb.js ---- */
/* JLDS behavior — Breadcrumb collapse. Clicking .jl-breadcrumb__ellipsis reveals
 * the collapsed middle items (.jl-breadcrumb__collapsed, initially `hidden`) and
 * hides the ellipsis itself. Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("breadcrumb", function (root) {
    root.querySelectorAll(".jl-breadcrumb__ellipsis").forEach(function (btn) {
      if (btn.__jlBc) return;
      btn.__jlBc = true;
      btn.addEventListener("click", function () {
        var nav = btn.closest(".jl-breadcrumb");
        if (!nav) return;
        nav.querySelectorAll(".jl-breadcrumb__collapsed").forEach(function (el) {
          el.hidden = false;
        });
        var item = btn.closest(".jl-breadcrumb__item");
        if (item) item.hidden = true;
      });
    });
  });
})();

/* ---- slider.js ---- */
/* JLDS behavior — Slider drag + keyboard. Requires core.js (or the all.js bundle).
 *
 * Markup contract (HTML users): on the root `.jl-slider` set data-min / data-max /
 * data-step (default 0 / 100 / 1) and optional data-suffix for the readout. Each
 * `.jl-slider__thumb` carries its initial data-value; two thumbs = a range slider.
 * On change the root emits a `jl-slider:change` CustomEvent ({ detail: { value } }).
 */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initSlider(sl) {
    if (sl.__jlSlider) return;
    sl.__jlSlider = true;

    var track = sl.querySelector(".jl-slider__track");
    if (!track) return;
    var fill = sl.querySelector(".jl-slider__fill");
    var readout = sl.querySelector(".jl-slider__value");
    var thumbs = Array.prototype.slice.call(sl.querySelectorAll(".jl-slider__thumb"));
    if (!thumbs.length) return;

    var min = parseFloat(sl.dataset.min) || 0;
    var max = parseFloat(sl.dataset.max);
    if (isNaN(max)) max = 100;
    var step = parseFloat(sl.dataset.step) || 1;
    var suffix = sl.dataset.suffix || "";
    var range = thumbs.length > 1;
    var vals = thumbs.map(function (t) {
      var v = parseFloat(t.dataset.value);
      return isNaN(v) ? min : v;
    });

    function pct(v) {
      return ((v - min) / (max - min)) * 100;
    }
    function round(v) {
      return Math.min(max, Math.max(min, Math.round((v - min) / step) * step + min));
    }

    function render() {
      thumbs.forEach(function (t, i) {
        t.style.left = pct(vals[i]) + "%";
        t.setAttribute("aria-valuenow", vals[i]);
      });
      if (range) {
        fill.style.left = pct(vals[0]) + "%";
        fill.style.right = 100 - pct(vals[1]) + "%";
      } else {
        fill.style.left = "0";
        fill.style.width = pct(vals[0]) + "%";
      }
      if (readout) {
        readout.textContent = range
          ? vals[0] + suffix + " – " + vals[1] + suffix
          : vals[0] + suffix;
      }
    }

    function fromX(x) {
      var r = track.getBoundingClientRect();
      var ratio = Math.min(1, Math.max(0, (x - r.left) / r.width));
      return round(min + ratio * (max - min));
    }

    function apply(i, v) {
      if (range) {
        if (i === 0) vals[0] = Math.min(v, vals[1]);
        else vals[1] = Math.max(v, vals[0]);
      } else {
        vals[0] = v;
      }
      render();
      sl.dispatchEvent(
        new CustomEvent("jl-slider:change", {
          detail: { value: range ? vals.slice() : vals[0] },
          bubbles: true,
        })
      );
    }

    track.addEventListener("pointerdown", function (e) {
      if (sl.classList.contains("jl-slider--disabled")) return;
      var v = fromX(e.clientX);
      var i = range ? (Math.abs(vals[0] - v) <= Math.abs(vals[1] - v) ? 0 : 1) : 0;
      apply(i, v);
      function move(ev) {
        apply(i, fromX(ev.clientX));
      }
      function up() {
        window.removeEventListener("pointermove", move);
        window.removeEventListener("pointerup", up);
      }
      window.addEventListener("pointermove", move);
      window.addEventListener("pointerup", up);
    });

    thumbs.forEach(function (t, i) {
      t.addEventListener("pointerdown", function (e) {
        e.stopPropagation();
      });
      t.addEventListener("keydown", function (e) {
        if (sl.classList.contains("jl-slider--disabled")) return;
        var big = step * 10;
        var v;
        switch (e.key) {
          case "ArrowRight":
          case "ArrowUp":
            v = vals[i] + step;
            break;
          case "ArrowLeft":
          case "ArrowDown":
            v = vals[i] - step;
            break;
          case "PageUp":
            v = vals[i] + big;
            break;
          case "PageDown":
            v = vals[i] - big;
            break;
          case "Home":
            v = min;
            break;
          case "End":
            v = max;
            break;
          default:
            return;
        }
        e.preventDefault();
        apply(i, round(v));
      });
    });

    render();
  }

  register("slider", function (root) {
    root.querySelectorAll(".jl-slider").forEach(initSlider);
  });
})();

/* ---- snippet.js ---- */
/* JLDS behavior — Snippet copy buttons. Requires core.js + util.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function copy(text) {
    var u = window.JLDS && window.JLDS.util;
    if (u && u.copy) u.copy(text);
  }

  function flash(btn, doneClass) {
    btn.classList.add(doneClass);
    setTimeout(function () {
      btn.classList.remove(doneClass);
    }, 1600);
  }

  function wire(root, btnSelector, wrapSelector, codeSelector, doneClass) {
    root.querySelectorAll(btnSelector).forEach(function (btn) {
      if (btn.__jlSnippet) return;
      btn.__jlSnippet = true;
      btn.addEventListener("click", function () {
        var wrap = btn.closest(wrapSelector);
        var code = wrap && wrap.querySelector(codeSelector);
        copy(code ? code.textContent : "");
        flash(btn, doneClass);
      });
    });
  }

  register("snippet", function (root) {
    wire(root, ".jl-snippet__copy", ".jl-snippet", ".jl-snippet__code", "jl-snippet__copy--done");
    wire(root, ".jl-codeblock__copy", ".jl-codeblock", "code", "jl-codeblock__copy--done");
  });
})();

/* ---- tag.js ---- */
/* JLDS behavior — Tag remove. Clicking .jl-tag__remove removes its .jl-tag.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("tag", function (root) {
    root.querySelectorAll(".jl-tag__remove").forEach(function (btn) {
      if (btn.__jlTag) return;
      btn.__jlTag = true;
      btn.addEventListener("click", function (e) {
        e.stopPropagation(); // don't trigger a selectable tag's own click
        var el = btn.closest(".jl-tag");
        if (el) el.remove();
      });
    });
  });
})();
