/* JLDS — behavior layer bundle. Auto-generated by scripts/build-js-bundle.mjs — do not edit by hand. */
/* Core + every component behavior. Progressive enhancement: load after your markup (defer is fine). */

/* ---- core.js ---- */
/* JLDS behavior layer — core.
 * Defines the global `JLDS` namespace and runs registered behaviors. Pure
 * progressive enhancement: markup renders without it; this only adds behavior.
 *
 *   JLDS.register(name, fn)  — a behavior; fn(root) wires up elements under root
 *   JLDS.init(root)          — (re)run all behaviors for a subtree (e.g. after fetch)
 *
 * Behaviors are idempotent (they tag handled elements), so init is safe to
 * call repeatedly. Component files may load before or after this file.
 */
(function () {
  var J = (window.JLDS = window.JLDS || {});
  if (J._core) return; // guard against double-load
  J._core = true;

  var behaviors = (J._behaviors = J._behaviors || {});
  var ready = false;

  function run(name, root) {
    try {
      behaviors[name](root);
    } catch (e) {
      console.error("[jlds:" + name + "]", e);
    }
  }

  J.register = function (name, fn) {
    behaviors[name] = fn;
    if (ready) run(name, document);
  };

  J.init = function (root) {
    root = root || document;
    Object.keys(behaviors).forEach(function (name) {
      run(name, root);
    });
  };

  function ignite() {
    ready = true;
    J.init(document);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", ignite);
  } else {
    ignite();
  }

  // Drain behaviors that registered before this core loaded.
  var pending = J._pending || [];
  J._pending = [];
  pending.forEach(function (p) {
    J.register(p[0], p[1]);
  });
})();

/* ---- util.js ---- */
/* JLDS behavior layer — shared utilities.
 * Framework-agnostic DOM primitives reused across component behaviors (and the
 * overlay components especially). Exposed as `JLDS.util`. Load before the
 * component behavior files (the all.js bundle orders this right after core).
 */
(function () {
  var J = (window.JLDS = window.JLDS || {});
  var util = (J.util = J.util || {});

  /* Copy text to the clipboard, with a hidden-textarea fallback for old/insecure contexts. */
  util.copy = function (text) {
    function legacy() {
      var ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand("copy");
      } catch (e) {
        /* noop */
      }
      document.body.removeChild(ta);
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).catch(legacy);
    }
    legacy();
    return Promise.resolve();
  };

  /* Call handler when a pointerdown lands outside `el`. Returns a cleanup fn. */
  util.onClickOutside = function (el, handler) {
    function onDown(e) {
      if (!el.contains(e.target)) handler(e);
    }
    document.addEventListener("pointerdown", onDown, true);
    return function () {
      document.removeEventListener("pointerdown", onDown, true);
    };
  };

  /* Call handler on Escape. Returns a cleanup fn. */
  util.onEscape = function (handler) {
    function onKey(e) {
      if (e.key === "Escape") handler(e);
    }
    document.addEventListener("keydown", onKey);
    return function () {
      document.removeEventListener("keydown", onKey);
    };
  };

  /* Lock body scroll (compensating for the scrollbar). Ref-counted so nested
   * overlays don't unlock early. Returns an unlock fn. */
  var locks = 0;
  var prevOverflow = "";
  var prevPad = "";
  util.lockScroll = function () {
    if (locks === 0) {
      var sbw = window.innerWidth - document.documentElement.clientWidth;
      prevOverflow = document.body.style.overflow;
      prevPad = document.body.style.paddingRight;
      document.body.style.overflow = "hidden";
      if (sbw > 0) document.body.style.paddingRight = sbw + "px";
    }
    locks++;
    var released = false;
    return function unlock() {
      if (released) return;
      released = true;
      locks = Math.max(0, locks - 1);
      if (locks === 0) {
        document.body.style.overflow = prevOverflow;
        document.body.style.paddingRight = prevPad;
      }
    };
  };

  var FOCUSABLE =
    'a[href],button:not([disabled]),textarea:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';

  /* Trap Tab focus within `el`, focus the first focusable, and restore focus to
   * the previously-focused element on release. Returns a release fn. */
  util.focusTrap = function (el) {
    var prev = document.activeElement;
    function focusables() {
      return Array.prototype.slice.call(el.querySelectorAll(FOCUSABLE)).filter(function (n) {
        return n.offsetParent !== null || n === document.activeElement;
      });
    }
    function onKey(e) {
      if (e.key !== "Tab") return;
      var f = focusables();
      if (!f.length) {
        e.preventDefault();
        return;
      }
      var first = f[0];
      var last = f[f.length - 1];
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    }
    el.addEventListener("keydown", onKey);
    var f = focusables();
    (f[0] || el).focus();
    return function release() {
      el.removeEventListener("keydown", onKey);
      if (prev && prev.focus) prev.focus();
    };
  };
})();

/* ---- accordion.js ---- */
/* JLDS behavior — Accordion. Clicking a .jl-acc-trigger opens/closes its
 * .jl-acc-item (toggles data-open + aria-expanded). Single-open by default;
 * set data-type="multiple" on the .jl-accordion to allow several open at once.
 * Emits jl-accordion:toggle. Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initAccordion(acc) {
    if (acc.__jlAcc) return;
    acc.__jlAcc = true;
    var multiple = acc.dataset.type === "multiple";
    var items = Array.prototype.slice.call(acc.querySelectorAll(".jl-acc-item"));

    function setOpen(item, open) {
      var trigger = item.querySelector(".jl-acc-trigger");
      if (open) item.setAttribute("data-open", "true");
      else item.removeAttribute("data-open");
      if (trigger) trigger.setAttribute("aria-expanded", open ? "true" : "false");
    }

    items.forEach(function (item) {
      var trigger = item.querySelector(".jl-acc-trigger");
      if (!trigger) return;
      trigger.addEventListener("click", function () {
        if (trigger.disabled) return;
        var open = item.getAttribute("data-open") === "true";
        if (!multiple) {
          items.forEach(function (o) {
            if (o !== item) setOpen(o, false);
          });
        }
        setOpen(item, !open);
        acc.dispatchEvent(
          new CustomEvent("jl-accordion:toggle", {
            detail: { value: trigger.getAttribute("aria-controls") || null, open: !open },
            bubbles: true,
          })
        );
      });
    });
  }

  register("accordion", function (root) {
    root.querySelectorAll(".jl-accordion").forEach(initAccordion);
  });
})();

/* ---- alert.js ---- */
/* JLDS behavior — Alert dismiss. Clicking .jl-alert__close removes its .jl-alert.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("alert", function (root) {
    root.querySelectorAll(".jl-alert__close").forEach(function (btn) {
      if (btn.__jlAlert) return;
      btn.__jlAlert = true;
      btn.addEventListener("click", function () {
        var el = btn.closest(".jl-alert");
        if (el) el.remove();
      });
    });
  });
})();

/* ---- banner.js ---- */
/* JLDS behavior — Banner dismiss. Clicking .jl-banner__close removes its .jl-banner.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("banner", function (root) {
    root.querySelectorAll(".jl-banner__close").forEach(function (btn) {
      if (btn.__jlBanner) return;
      btn.__jlBanner = true;
      btn.addEventListener("click", function () {
        var el = btn.closest(".jl-banner");
        if (el) el.remove();
      });
    });
  });
})();

/* ---- breadcrumb.js ---- */
/* JLDS behavior — Breadcrumb collapse. Clicking .jl-breadcrumb__ellipsis reveals
 * the collapsed middle items (.jl-breadcrumb__collapsed, initially `hidden`) and
 * hides the ellipsis itself. Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("breadcrumb", function (root) {
    root.querySelectorAll(".jl-breadcrumb__ellipsis").forEach(function (btn) {
      if (btn.__jlBc) return;
      btn.__jlBc = true;
      btn.addEventListener("click", function () {
        var nav = btn.closest(".jl-breadcrumb");
        if (!nav) return;
        nav.querySelectorAll(".jl-breadcrumb__collapsed").forEach(function (el) {
          el.hidden = false;
        });
        var item = btn.closest(".jl-breadcrumb__item");
        if (item) item.hidden = true;
      });
    });
  });
})();

/* ---- combobox.js ---- */
/* JLDS behavior — Combobox (single-select, declarative). Enhances a .jl-combobox
 * whose options are in the DOM (.jl-combobox__opt[data-value]): open on focus,
 * filter by the typed text, arrow/enter/escape keyboard nav, and single-select.
 * Emits jl-combobox:change { value }. Requires core.js + util.js (or all.js).
 * (Multiple/chips, creatable, and async are React/Vue-only.) */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  var CHECK =
    '<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M13 4.5 6.5 11 3 7.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';

  function initCombobox(cb) {
    if (cb.__jlCombobox) return;
    cb.__jlCombobox = true;

    var control = cb.querySelector(".jl-combobox__control");
    var input = cb.querySelector(".jl-combobox__input");
    var single = cb.querySelector(".jl-combobox__single");
    var pop = cb.querySelector(".jl-combobox__pop");
    var opts = Array.prototype.slice.call(cb.querySelectorAll(".jl-combobox__opt"));
    if (!input || !pop || !opts.length) return;

    var active = 0;
    var cleanup = null;

    function labelOf(opt) {
      var l = opt.querySelector(".jl-combobox__opt-label");
      return (l ? l.textContent : opt.textContent).trim();
    }
    function visible() {
      return opts.filter(function (o) {
        return o.style.display !== "none" && o.getAttribute("aria-disabled") !== "true";
      });
    }
    function setActive(i) {
      var vis = visible();
      active = Math.max(0, Math.min(vis.length - 1, i));
      opts.forEach(function (o) { o.removeAttribute("data-active"); });
      if (vis[active]) vis[active].setAttribute("data-active", "true");
    }
    function filter() {
      var q = input.value.toLowerCase();
      opts.forEach(function (o) {
        o.style.display = labelOf(o).toLowerCase().indexOf(q) >= 0 ? "" : "none";
      });
      if (single) single.style.display = input.value ? "none" : "";
      setActive(0);
    }
    function open() {
      if (!pop.hidden) return;
      pop.hidden = false;
      cb.classList.add("jl-combobox--open");
      input.setAttribute("aria-expanded", "true");
      filter();
      var u = window.JLDS && window.JLDS.util;
      cleanup = u && u.onClickOutside ? u.onClickOutside(cb, close) : function () {};
    }
    function close() {
      if (pop.hidden) return;
      pop.hidden = true;
      cb.classList.remove("jl-combobox--open");
      input.setAttribute("aria-expanded", "false");
      input.value = "";
      if (single) single.style.display = "";
      if (cleanup) { cleanup(); cleanup = null; }
    }
    function choose(opt) {
      if (!opt || opt.getAttribute("aria-disabled") === "true") return;
      cb.dataset.value = opt.dataset.value || labelOf(opt);
      if (single) {
        single.textContent = labelOf(opt);
        single.classList.remove("jl-combobox__single--placeholder");
      }
      opts.forEach(function (o) {
        o.setAttribute("aria-selected", o === opt ? "true" : "false");
        var c = o.querySelector(".jl-combobox__opt-check");
        if (o === opt && !c) {
          var s = document.createElement("span");
          s.className = "jl-combobox__opt-check";
          s.innerHTML = CHECK;
          o.appendChild(s);
        } else if (o !== opt && c) {
          c.remove();
        }
      });
      close();
      cb.dispatchEvent(new CustomEvent("jl-combobox:change", { detail: { value: cb.dataset.value }, bubbles: true }));
    }

    if (control) control.addEventListener("click", function () { open(); input.focus(); });
    input.addEventListener("focus", open);
    input.addEventListener("input", function () { if (pop.hidden) open(); filter(); });
    input.addEventListener("keydown", function (e) {
      if (e.key === "ArrowDown") { e.preventDefault(); if (pop.hidden) return open(); setActive(active + 1); }
      else if (e.key === "ArrowUp") { e.preventDefault(); setActive(active - 1); }
      else if (e.key === "Enter") { e.preventDefault(); choose(visible()[active]); }
      else if (e.key === "Escape") { if (!pop.hidden) { e.preventDefault(); close(); } }
    });
    opts.forEach(function (opt) {
      opt.addEventListener("mousemove", function () {
        var i = visible().indexOf(opt);
        if (i >= 0) setActive(i);
      });
      opt.addEventListener("click", function () { choose(opt); });
    });
  }

  register("combobox", function (root) {
    root.querySelectorAll(".jl-combobox").forEach(initCombobox);
  });
})();

/* ---- command-palette.js ---- */
/* JLDS behavior — CommandPalette (declarative HTML). Enhances a
 * .jl-cmdk__overlay[hidden]: a global ⌘K/Ctrl-K toggle (or data-key), fuzzy
 * filter over the .jl-cmdk__item rows (matches text + data-keywords), arrow/
 * enter/escape nav, overlay-click + Esc close, and scroll-lock via JLDS.util.
 * A `[data-cmdk-trigger]` element (optional data-cmdk-target="#id") also opens it.
 * Requires core.js + util.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initOverlay(overlay) {
    if (overlay.__jlCmdk) return;
    overlay.__jlCmdk = true;
    var input = overlay.querySelector(".jl-cmdk__input");
    var list = overlay.querySelector(".jl-cmdk__list");
    var items = Array.prototype.slice.call(overlay.querySelectorAll(".jl-cmdk__item"));
    var emptyEl = overlay.querySelector(".jl-cmdk__empty");
    var key = (overlay.dataset.key || "k").toLowerCase();
    var active = 0;
    var unlock = null;

    function text(it) {
      var l = it.querySelector(".jl-cmdk__item-label");
      return ((l ? l.textContent : it.textContent) + " " + (it.dataset.keywords || "")).toLowerCase();
    }
    function visible() {
      return items.filter(function (it) {
        return it.style.display !== "none" && it.getAttribute("aria-disabled") !== "true";
      });
    }
    function setActive(i) {
      var vis = visible();
      active = Math.max(0, Math.min(vis.length - 1, i));
      items.forEach(function (it) { it.removeAttribute("data-active"); });
      var el = vis[active];
      if (!el) return;
      el.setAttribute("data-active", "true");
      if (list) {
        var top = el.offsetTop;
        var bottom = top + el.offsetHeight;
        if (top < list.scrollTop) list.scrollTop = top - 8;
        else if (bottom > list.scrollTop + list.clientHeight) list.scrollTop = bottom - list.clientHeight + 8;
      }
    }
    function filter() {
      var tokens = (input ? input.value : "").toLowerCase().split(/\s+/).filter(Boolean);
      var any = false;
      items.forEach(function (it) {
        var ok = tokens.every(function (t) { return text(it).indexOf(t) >= 0; });
        it.style.display = ok ? "" : "none";
        if (ok) any = true;
      });
      if (emptyEl) emptyEl.style.display = any ? "none" : "";
      setActive(0);
    }
    function open() {
      if (!overlay.hidden) return;
      overlay.hidden = false;
      var u = window.JLDS && window.JLDS.util;
      unlock = u && u.lockScroll ? u.lockScroll() : function () {};
      if (input) input.value = "";
      filter();
      setTimeout(function () { input && input.focus(); }, 20);
    }
    function close() {
      if (overlay.hidden) return;
      overlay.hidden = true;
      if (unlock) { unlock(); unlock = null; }
    }
    overlay.__cmdkOpen = open;
    overlay.__cmdkClose = close;

    document.addEventListener("keydown", function (e) {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === key) {
        e.preventDefault();
        if (overlay.hidden) open();
        else close();
      }
    });
    overlay.addEventListener("mousedown", function (e) {
      if (e.target === overlay) close();
    });
    if (input) {
      input.addEventListener("input", filter);
      input.addEventListener("keydown", function (e) {
        if (e.key === "ArrowDown") { e.preventDefault(); setActive(active + 1); }
        else if (e.key === "ArrowUp") { e.preventDefault(); setActive(active - 1); }
        else if (e.key === "Enter") { e.preventDefault(); var it = visible()[active]; if (it) it.click(); }
        else if (e.key === "Escape") { e.preventDefault(); close(); }
      });
    }
    items.forEach(function (it) {
      it.addEventListener("mousemove", function () {
        var i = visible().indexOf(it);
        if (i >= 0) setActive(i);
      });
      it.addEventListener("click", function () {
        if (it.getAttribute("aria-disabled") === "true") return;
        close();
      });
    });
    if (!overlay.hasAttribute("hidden")) overlay.hidden = true;
  }

  register("cmdk", function (root) {
    root.querySelectorAll(".jl-cmdk__overlay").forEach(initOverlay);
    root.querySelectorAll("[data-cmdk-trigger]").forEach(function (trigger) {
      if (trigger.__jlCmdkTrig) return;
      trigger.__jlCmdkTrig = true;
      trigger.addEventListener("click", function () {
        var sel = trigger.getAttribute("data-cmdk-target");
        var overlay = sel ? document.querySelector(sel) : document.querySelector(".jl-cmdk__overlay");
        if (overlay && overlay.__cmdkOpen) overlay.__cmdkOpen();
      });
    });
  });
})();

/* ---- dialog.js ---- */
/* JLDS behavior — Dialog. A modal overlay (.jl-dialog__overlay[hidden]) opened by
 * a [data-dialog-trigger] (optional data-dialog-target="#id"); closes on overlay
 * click, Esc, .jl-dialog__close, or [data-dialog-close]. While open it locks body
 * scroll and traps focus via JLDS.util. Requires core.js + util.js (or all.js). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initOverlay(overlay) {
    if (overlay.__jlDialog) return;
    overlay.__jlDialog = true;
    var panel = overlay.querySelector(".jl-dialog");
    var cleanup = null;

    function close() {
      if (overlay.hidden) return;
      overlay.hidden = true;
      if (cleanup) {
        cleanup();
        cleanup = null;
      }
    }
    function open() {
      if (!overlay.hidden) return;
      overlay.hidden = false;
      var u = window.JLDS && window.JLDS.util;
      var unlock = u && u.lockScroll ? u.lockScroll() : function () {};
      var release = u && u.focusTrap && panel ? u.focusTrap(panel) : function () {};
      var offEsc = u && u.onEscape ? u.onEscape(close) : function () {};
      cleanup = function () {
        unlock();
        release();
        offEsc();
      };
    }
    overlay.__open = open;
    overlay.__close = close;

    overlay.addEventListener("mousedown", function (e) {
      if (e.target === overlay) close();
    });
    overlay.querySelectorAll(".jl-dialog__close, [data-dialog-close]").forEach(function (b) {
      b.addEventListener("click", close);
    });
    if (!overlay.hasAttribute("hidden")) overlay.hidden = true;
  }

  register("dialog", function (root) {
    root.querySelectorAll(".jl-dialog__overlay").forEach(initOverlay);
    root.querySelectorAll("[data-dialog-trigger]").forEach(function (trigger) {
      if (trigger.__jlDialogTrig) return;
      trigger.__jlDialogTrig = true;
      trigger.addEventListener("click", function () {
        var sel = trigger.getAttribute("data-dialog-target");
        var overlay = sel ? document.querySelector(sel) : document.querySelector(".jl-dialog__overlay");
        if (overlay && overlay.__open) overlay.__open();
      });
    });
  });
})();

/* ---- drawer.js ---- */
/* JLDS behavior — Drawer. A slide-in overlay (.jl-drawer__overlay[hidden][data-side])
 * opened by a [data-drawer-trigger] (optional data-drawer-target="#id"); closes on
 * overlay click, Esc, .jl-drawer__close, or [data-drawer-close]. Locks body scroll
 * and traps focus via JLDS.util while open. Requires core.js + util.js (or all.js). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initOverlay(overlay) {
    if (overlay.__jlDrawer) return;
    overlay.__jlDrawer = true;
    var panel = overlay.querySelector(".jl-drawer");
    var cleanup = null;

    function close() {
      if (overlay.hidden) return;
      overlay.hidden = true;
      if (cleanup) {
        cleanup();
        cleanup = null;
      }
    }
    function open() {
      if (!overlay.hidden) return;
      overlay.hidden = false;
      var u = window.JLDS && window.JLDS.util;
      var unlock = u && u.lockScroll ? u.lockScroll() : function () {};
      var release = u && u.focusTrap && panel ? u.focusTrap(panel) : function () {};
      var offEsc = u && u.onEscape ? u.onEscape(close) : function () {};
      cleanup = function () {
        unlock();
        release();
        offEsc();
      };
    }
    overlay.__open = open;
    overlay.__close = close;

    overlay.addEventListener("mousedown", function (e) {
      if (e.target === overlay) close();
    });
    overlay.querySelectorAll(".jl-drawer__close, [data-drawer-close]").forEach(function (b) {
      b.addEventListener("click", close);
    });
    if (!overlay.hasAttribute("hidden")) overlay.hidden = true;
  }

  register("drawer", function (root) {
    root.querySelectorAll(".jl-drawer__overlay").forEach(initOverlay);
    root.querySelectorAll("[data-drawer-trigger]").forEach(function (trigger) {
      if (trigger.__jlDrawerTrig) return;
      trigger.__jlDrawerTrig = true;
      trigger.addEventListener("click", function () {
        var sel = trigger.getAttribute("data-drawer-target");
        var overlay = sel ? document.querySelector(sel) : document.querySelector(".jl-drawer__overlay");
        if (overlay && overlay.__open) overlay.__open();
      });
    });
  });
})();

/* ---- dropdown-menu.js ---- */
/* JLDS behavior — DropdownMenu. Click the trigger to open the .jl-menu__pop
 * (initially `hidden`); closes on item click, outside-click, or Esc (via
 * JLDS.util). Requires core.js + util.js (or the all.js bundle).
 * Contract: .jl-menu holds a trigger (first <button> / [data-menu-trigger]) and
 * a .jl-menu__pop[hidden] with .jl-menu__item buttons. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initMenu(menu) {
    if (menu.__jlMenu) return;
    menu.__jlMenu = true;
    var trigger = menu.querySelector("[data-menu-trigger]") || menu.querySelector("button");
    var pop = menu.querySelector(".jl-menu__pop");
    if (!trigger || !pop) return;

    var cleanup = null;
    function close() {
      if (pop.hidden) return;
      pop.hidden = true;
      trigger.setAttribute("aria-expanded", "false");
      if (cleanup) {
        cleanup();
        cleanup = null;
      }
    }
    function open() {
      pop.hidden = false;
      trigger.setAttribute("aria-expanded", "true");
      var u = window.JLDS && window.JLDS.util;
      var a = u && u.onClickOutside ? u.onClickOutside(menu, close) : function () {};
      var b = u && u.onEscape ? u.onEscape(close) : function () {};
      cleanup = function () {
        a();
        b();
      };
    }

    trigger.setAttribute("aria-haspopup", "menu");
    trigger.setAttribute("aria-expanded", "false");
    if (!pop.hasAttribute("hidden")) pop.hidden = true;

    trigger.addEventListener("click", function (e) {
      e.stopPropagation();
      if (pop.hidden) open();
      else close();
    });
    pop.querySelectorAll(".jl-menu__item").forEach(function (item) {
      item.addEventListener("click", function () {
        if (item.getAttribute("aria-disabled") === "true") return;
        close();
      });
    });
  }

  register("menu", function (root) {
    root.querySelectorAll(".jl-menu").forEach(initMenu);
  });
})();

/* ---- number-input.js ---- */
/* JLDS behavior — NumberInput steppers + keyboard. Requires core.js (or all.js).
 * Contract: .jl-number with data-min / data-max / data-step / data-precision (all
 * optional); a .jl-number__input (set its `value` for the initial number); and
 * .jl-number__btn--dec / --inc buttons. Emits jl-number:change on commit. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function decimals(s) {
    s = String(s);
    return s.indexOf(".") >= 0 ? s.split(".")[1].length : 0;
  }

  function initNumber(el) {
    if (el.__jlNum) return;
    el.__jlNum = true;

    var input = el.querySelector(".jl-number__input");
    if (!input) return;
    var dec = el.querySelector(".jl-number__btn--dec");
    var inc = el.querySelector(".jl-number__btn--inc");

    var min = el.dataset.min != null ? parseFloat(el.dataset.min) : -Infinity;
    var max = el.dataset.max != null ? parseFloat(el.dataset.max) : Infinity;
    var step = parseFloat(el.dataset.step) || 1;
    var prec = el.dataset.precision != null ? parseInt(el.dataset.precision, 10) : decimals(step);

    function clamp(n) {
      return Math.min(max, Math.max(min, n));
    }
    function round(n) {
      return Number(n.toFixed(prec));
    }
    function cur() {
      var n = parseFloat(input.value);
      return isNaN(n) ? null : n;
    }
    function sync() {
      var c = cur();
      if (dec) dec.disabled = c != null && c <= min;
      if (inc) inc.disabled = c != null && c >= max;
      input.setAttribute("aria-valuenow", c == null ? "" : c);
    }
    function commit(n) {
      var next = n == null || isNaN(n) ? "" : round(clamp(n));
      input.value = next === "" ? "" : String(next);
      sync();
      el.dispatchEvent(
        new CustomEvent("jl-number:change", {
          detail: { value: next === "" ? null : next },
          bubbles: true,
        })
      );
    }
    function bump(dir) {
      var b = cur();
      var start = b == null ? (isFinite(min) ? min : 0) : b;
      commit(start + dir * step);
    }

    if (dec) dec.addEventListener("click", function () { bump(-1); });
    if (inc) inc.addEventListener("click", function () { bump(1); });
    input.addEventListener("input", function () {
      if (!/^-?\d*\.?\d*$/.test(input.value)) {
        input.value = input.value.replace(/[^\d.-]/g, "");
      }
      sync();
    });
    input.addEventListener("blur", function () { commit(cur()); });
    input.addEventListener("keydown", function (e) {
      if (e.key === "ArrowUp") { e.preventDefault(); bump(1); }
      else if (e.key === "ArrowDown") { e.preventDefault(); bump(-1); }
    });

    // aria bounds
    if (isFinite(min)) input.setAttribute("aria-valuemin", min);
    if (isFinite(max)) input.setAttribute("aria-valuemax", max);
    sync();
  }

  register("number", function (root) {
    root.querySelectorAll(".jl-number").forEach(initNumber);
  });
})();

/* ---- popover.js ---- */
/* JLDS behavior — Popover. Click the trigger to open the .jl-popover__pop panel
 * (initially `hidden`); closes on outside-click or Esc via JLDS.util. Emits
 * jl-popover:toggle. Requires core.js + util.js (or the all.js bundle).
 * Contract: .jl-popover holds a trigger (first <button>, or [data-popover-trigger])
 * and a `.jl-popover__pop[hidden]` panel. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initPopover(pop) {
    if (pop.__jlPop) return;
    pop.__jlPop = true;
    var trigger = pop.querySelector("[data-popover-trigger]") || pop.querySelector("button");
    var panel = pop.querySelector(".jl-popover__pop");
    if (!trigger || !panel) return;

    var cleanup = null;

    function close() {
      if (panel.hidden) return;
      panel.hidden = true;
      trigger.setAttribute("aria-expanded", "false");
      if (cleanup) {
        cleanup();
        cleanup = null;
      }
      pop.dispatchEvent(new CustomEvent("jl-popover:toggle", { detail: { open: false }, bubbles: true }));
    }
    function open() {
      panel.hidden = false;
      trigger.setAttribute("aria-expanded", "true");
      var u = window.JLDS && window.JLDS.util;
      var offOutside = u && u.onClickOutside ? u.onClickOutside(pop, close) : function () {};
      var offEsc = u && u.onEscape ? u.onEscape(close) : function () {};
      cleanup = function () {
        offOutside();
        offEsc();
      };
      pop.dispatchEvent(new CustomEvent("jl-popover:toggle", { detail: { open: true }, bubbles: true }));
    }

    trigger.setAttribute("aria-haspopup", "dialog");
    trigger.setAttribute("aria-expanded", "false");
    if (!panel.hasAttribute("hidden")) panel.hidden = true;

    trigger.addEventListener("click", function (e) {
      e.stopPropagation();
      if (panel.hidden) open();
      else close();
    });
  }

  register("popover", function (root) {
    root.querySelectorAll(".jl-popover").forEach(initPopover);
  });
})();

/* ---- segmented-control.js ---- */
/* JLDS behavior — SegmentedControl. Click an option to select it; the thumb slides
 * to it. Emits jl-segmented:change. Requires core.js (or the all.js bundle).
 * Contract: .jl-segmented holds a .jl-segmented__thumb and .jl-segmented__option
 * buttons (one with aria-checked="true"); optional data-value per option. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initSeg(seg) {
    if (seg.__jlSeg) return;
    seg.__jlSeg = true;

    var thumb = seg.querySelector(".jl-segmented__thumb");
    var opts = Array.prototype.slice.call(seg.querySelectorAll(".jl-segmented__option"));
    if (!opts.length) return;

    function moveThumb(btn) {
      if (!thumb || !btn) return;
      var pad = parseFloat(getComputedStyle(seg).paddingLeft) || 0;
      thumb.style.transform = "translateX(" + (btn.offsetLeft - pad) + "px)";
      thumb.style.width = btn.offsetWidth + "px";
    }
    function selected() {
      return seg.querySelector('.jl-segmented__option[aria-checked="true"]') || opts[0];
    }

    opts.forEach(function (btn) {
      btn.addEventListener("click", function () {
        if (btn.disabled || btn.getAttribute("aria-checked") === "true") return;
        opts.forEach(function (o) {
          o.setAttribute("aria-checked", o === btn ? "true" : "false");
        });
        moveThumb(btn);
        seg.dispatchEvent(
          new CustomEvent("jl-segmented:change", {
            detail: { value: btn.dataset.value || btn.textContent.trim() },
            bubbles: true,
          })
        );
      });
    });

    moveThumb(selected());
    window.addEventListener("resize", function () {
      moveThumb(selected());
    });
    if (document.fonts && document.fonts.ready) {
      document.fonts.ready.then(function () {
        moveThumb(selected());
      });
    }
  }

  register("segmented", function (root) {
    root.querySelectorAll(".jl-segmented").forEach(initSeg);
  });
})();

/* ---- slider.js ---- */
/* JLDS behavior — Slider drag + keyboard. Requires core.js (or the all.js bundle).
 *
 * Markup contract (HTML users): on the root `.jl-slider` set data-min / data-max /
 * data-step (default 0 / 100 / 1) and optional data-suffix for the readout. Each
 * `.jl-slider__thumb` carries its initial data-value; two thumbs = a range slider.
 * On change the root emits a `jl-slider:change` CustomEvent ({ detail: { value } }).
 */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initSlider(sl) {
    if (sl.__jlSlider) return;
    sl.__jlSlider = true;

    var track = sl.querySelector(".jl-slider__track");
    if (!track) return;
    var fill = sl.querySelector(".jl-slider__fill");
    var readout = sl.querySelector(".jl-slider__value");
    var thumbs = Array.prototype.slice.call(sl.querySelectorAll(".jl-slider__thumb"));
    if (!thumbs.length) return;

    var min = parseFloat(sl.dataset.min) || 0;
    var max = parseFloat(sl.dataset.max);
    if (isNaN(max)) max = 100;
    var step = parseFloat(sl.dataset.step) || 1;
    var suffix = sl.dataset.suffix || "";
    var range = thumbs.length > 1;
    var vals = thumbs.map(function (t) {
      var v = parseFloat(t.dataset.value);
      return isNaN(v) ? min : v;
    });

    function pct(v) {
      return ((v - min) / (max - min)) * 100;
    }
    function round(v) {
      return Math.min(max, Math.max(min, Math.round((v - min) / step) * step + min));
    }

    function render() {
      thumbs.forEach(function (t, i) {
        t.style.left = pct(vals[i]) + "%";
        t.setAttribute("aria-valuenow", vals[i]);
      });
      if (range) {
        fill.style.left = pct(vals[0]) + "%";
        fill.style.right = 100 - pct(vals[1]) + "%";
      } else {
        fill.style.left = "0";
        fill.style.width = pct(vals[0]) + "%";
      }
      if (readout) {
        readout.textContent = range
          ? vals[0] + suffix + " – " + vals[1] + suffix
          : vals[0] + suffix;
      }
    }

    function fromX(x) {
      var r = track.getBoundingClientRect();
      var ratio = Math.min(1, Math.max(0, (x - r.left) / r.width));
      return round(min + ratio * (max - min));
    }

    function apply(i, v) {
      if (range) {
        if (i === 0) vals[0] = Math.min(v, vals[1]);
        else vals[1] = Math.max(v, vals[0]);
      } else {
        vals[0] = v;
      }
      render();
      sl.dispatchEvent(
        new CustomEvent("jl-slider:change", {
          detail: { value: range ? vals.slice() : vals[0] },
          bubbles: true,
        })
      );
    }

    track.addEventListener("pointerdown", function (e) {
      if (sl.classList.contains("jl-slider--disabled")) return;
      var v = fromX(e.clientX);
      var i = range ? (Math.abs(vals[0] - v) <= Math.abs(vals[1] - v) ? 0 : 1) : 0;
      apply(i, v);
      function move(ev) {
        apply(i, fromX(ev.clientX));
      }
      function up() {
        window.removeEventListener("pointermove", move);
        window.removeEventListener("pointerup", up);
      }
      window.addEventListener("pointermove", move);
      window.addEventListener("pointerup", up);
    });

    thumbs.forEach(function (t, i) {
      t.addEventListener("pointerdown", function (e) {
        e.stopPropagation();
      });
      t.addEventListener("keydown", function (e) {
        if (sl.classList.contains("jl-slider--disabled")) return;
        var big = step * 10;
        var v;
        switch (e.key) {
          case "ArrowRight":
          case "ArrowUp":
            v = vals[i] + step;
            break;
          case "ArrowLeft":
          case "ArrowDown":
            v = vals[i] - step;
            break;
          case "PageUp":
            v = vals[i] + big;
            break;
          case "PageDown":
            v = vals[i] - big;
            break;
          case "Home":
            v = min;
            break;
          case "End":
            v = max;
            break;
          default:
            return;
        }
        e.preventDefault();
        apply(i, round(v));
      });
    });

    render();
  }

  register("slider", function (root) {
    root.querySelectorAll(".jl-slider").forEach(initSlider);
  });
})();

/* ---- snippet.js ---- */
/* JLDS behavior — Snippet copy buttons. Requires core.js + util.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function copy(text) {
    var u = window.JLDS && window.JLDS.util;
    if (u && u.copy) u.copy(text);
  }

  function flash(btn, doneClass) {
    btn.classList.add(doneClass);
    setTimeout(function () {
      btn.classList.remove(doneClass);
    }, 1600);
  }

  function wire(root, btnSelector, wrapSelector, codeSelector, doneClass) {
    root.querySelectorAll(btnSelector).forEach(function (btn) {
      if (btn.__jlSnippet) return;
      btn.__jlSnippet = true;
      btn.addEventListener("click", function () {
        var wrap = btn.closest(wrapSelector);
        var code = wrap && wrap.querySelector(codeSelector);
        copy(code ? code.textContent : "");
        flash(btn, doneClass);
      });
    });
  }

  register("snippet", function (root) {
    wire(root, ".jl-snippet__copy", ".jl-snippet", ".jl-snippet__code", "jl-snippet__copy--done");
    wire(root, ".jl-codeblock__copy", ".jl-codeblock", "code", "jl-codeblock__copy--done");
  });
})();

/* ---- table.js ---- */
/* JLDS behavior — Table. Opt-in client-side enhancements for plain-HTML tables:
 *   - Sorting: clicking a sortable header (a `.jl-th__btn`) sorts the tbody rows
 *     by that column, cycling asc/desc. Numeric columns (.jl-th--num) sort by value.
 *     Emits jl-table:sort { column, direction }.
 *   - Selection: a `.jl-table__check` checkbox per row toggles .jl-tr--selected; a
 *     header `.jl-table__check[data-select-all]` toggles all (with indeterminate).
 *     Emits jl-table:select { values }.
 * Requires core.js (or the all.js bundle). In React/Vue, sort/selection are
 * controlled via props — this is for the no-framework path only.
 */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  var ICONS = {
    none: '<path d="M8 9l4-4 4 4M8 15l4 4 4-4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>',
    asc: '<path d="M8 14l4-4 4 4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>',
    desc: '<path d="M8 10l4 4 4-4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>',
  };

  function cellText(row, idx) {
    var c = row.children[idx];
    return c ? c.textContent.trim() : "";
  }

  function initSort(table) {
    var head = table.querySelector(".jl-table__head tr") || table.querySelector("thead tr");
    var body = table.querySelector(".jl-table__body") || table.querySelector("tbody");
    if (!head || !body) return;
    var ths = Array.prototype.slice.call(head.children);

    ths.forEach(function (th, idx) {
      var btn = th.querySelector(".jl-th__btn");
      if (!btn) return;
      var svg = th.querySelector(".jl-th__sort svg");
      btn.addEventListener("click", function () {
        var dir = th.getAttribute("aria-sort") === "ascending" ? "desc" : "asc";
        ths.forEach(function (o) {
          if (o === th) return;
          o.setAttribute("aria-sort", "none");
          o.classList.remove("jl-th--active");
          var s = o.querySelector(".jl-th__sort svg");
          if (s) s.innerHTML = ICONS.none;
        });
        th.setAttribute("aria-sort", dir === "asc" ? "ascending" : "descending");
        th.classList.add("jl-th--active");
        if (svg) svg.innerHTML = ICONS[dir];

        var numeric = th.classList.contains("jl-th--num");
        var rows = Array.prototype.slice.call(body.querySelectorAll("tr"));
        rows.sort(function (a, b) {
          var av = cellText(a, idx);
          var bv = cellText(b, idx);
          if (numeric) {
            av = parseFloat(av.replace(/[^0-9.eE+-]/g, ""));
            bv = parseFloat(bv.replace(/[^0-9.eE+-]/g, ""));
          }
          if (av < bv) return dir === "asc" ? -1 : 1;
          if (av > bv) return dir === "asc" ? 1 : -1;
          return 0;
        });
        rows.forEach(function (r) {
          body.appendChild(r);
        });
        table.dispatchEvent(
          new CustomEvent("jl-table:sort", { detail: { column: idx, direction: dir }, bubbles: true })
        );
      });
    });
  }

  function initSelect(table) {
    var all = table.querySelector(".jl-table__check[data-select-all]");
    var checks = Array.prototype.slice.call(
      table.querySelectorAll(".jl-table__body .jl-table__check")
    );
    if (!checks.length) return;

    function rowOf(cb) {
      return cb.closest("tr");
    }
    function selectedValues() {
      return checks
        .filter(function (c) { return c.checked; })
        .map(function (c) {
          var tr = rowOf(c);
          return c.value || (tr && tr.dataset.value) || "";
        });
    }
    function emit() {
      table.dispatchEvent(
        new CustomEvent("jl-table:select", { detail: { values: selectedValues() }, bubbles: true })
      );
    }
    function syncAll() {
      if (!all) return;
      var n = checks.filter(function (c) { return c.checked; }).length;
      all.checked = n === checks.length;
      all.indeterminate = n > 0 && n < checks.length;
    }
    function paint(cb) {
      var tr = rowOf(cb);
      if (tr) {
        tr.classList.toggle("jl-tr--selected", cb.checked);
        tr.setAttribute("aria-selected", cb.checked ? "true" : "false");
      }
    }

    checks.forEach(function (cb) {
      cb.addEventListener("change", function () {
        paint(cb);
        syncAll();
        emit();
      });
    });
    if (all) {
      all.addEventListener("change", function () {
        checks.forEach(function (cb) {
          cb.checked = all.checked;
          paint(cb);
        });
        all.indeterminate = false;
        emit();
      });
    }
    syncAll();
  }

  register("table", function (root) {
    root.querySelectorAll(".jl-table").forEach(function (table) {
      if (table.__jlTable) return;
      table.__jlTable = true;
      initSort(table);
      initSelect(table);
    });
  });
})();

/* ---- tabs.js ---- */
/* JLDS behavior — Tabs. Click or arrow-key to switch tabs; if a tab has
 * aria-controls, its panel is shown and the others hidden. Emits jl-tabs:change.
 * Requires core.js (or the all.js bundle).
 * Contract: .jl-tabs holds .jl-tab buttons (role="tab", aria-selected). Optional
 * aria-controls="panelId" pairs each tab with an element to toggle. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initTabs(strip) {
    if (strip.__jlTabs) return;
    strip.__jlTabs = true;

    var tabs = Array.prototype.slice.call(strip.querySelectorAll(".jl-tab"));
    if (!tabs.length) return;

    function panelFor(tab) {
      var id = tab.getAttribute("aria-controls");
      return id ? document.getElementById(id) : null;
    }
    function applyState(active, emit) {
      tabs.forEach(function (t) {
        var on = t === active;
        t.setAttribute("aria-selected", on ? "true" : "false");
        t.tabIndex = on ? 0 : -1;
        var p = panelFor(t);
        if (p) p.hidden = !on;
      });
      if (emit) {
        strip.dispatchEvent(
          new CustomEvent("jl-tabs:change", {
            detail: { value: active.dataset.value || active.textContent.trim() },
            bubbles: true,
          })
        );
      }
    }

    tabs.forEach(function (tab, i) {
      tab.addEventListener("click", function () {
        applyState(tab, true);
      });
      tab.addEventListener("keydown", function (e) {
        var next;
        if (e.key === "ArrowRight") next = tabs[(i + 1) % tabs.length];
        else if (e.key === "ArrowLeft") next = tabs[(i - 1 + tabs.length) % tabs.length];
        else if (e.key === "Home") next = tabs[0];
        else if (e.key === "End") next = tabs[tabs.length - 1];
        else return;
        e.preventDefault();
        next.focus();
        applyState(next, true);
      });
    });

    var selected = strip.querySelector('.jl-tab[aria-selected="true"]') || tabs[0];
    applyState(selected, false);
  }

  register("tabs", function (root) {
    root.querySelectorAll(".jl-tabs").forEach(initTabs);
  });
})();

/* ---- tag.js ---- */
/* JLDS behavior — Tag remove. Clicking .jl-tag__remove removes its .jl-tag.
 * Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  register("tag", function (root) {
    root.querySelectorAll(".jl-tag__remove").forEach(function (btn) {
      if (btn.__jlTag) return;
      btn.__jlTag = true;
      btn.addEventListener("click", function (e) {
        e.stopPropagation(); // don't trigger a selectable tag's own click
        var el = btn.closest(".jl-tag");
        if (el) el.remove();
      });
    });
  });
})();

/* ---- toast.js ---- */
/* JLDS behavior — Toast. Imperative API for plain HTML: call JLDS.toast(...) from
 * anywhere; it lazily creates a positioned toaster container and stacks toasts
 * (tones, action, auto-dismiss). Requires core.js (or the all.js bundle).
 *
 *   JLDS.toast("Saved")                         // neutral
 *   JLDS.toast.success("Profile updated")
 *   JLDS.toast({ title: "Deploy failed", description: "...", tone: "danger",
 *               action: { label: "Retry", onClick: fn }, duration: Infinity })
 *   var el = JLDS.toast(...); JLDS.toast.dismiss(el)
 */
(function () {
  var J = (window.JLDS = window.JLDS || {});

  var ICONS = {
    success: '<path d="M8 12.5l2.5 2.5 5.5-6" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>',
    warning: '<path d="M12 8.5v4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="12" cy="16" r="0.6" fill="currentColor" stroke="none"/>',
    danger: '<path d="M12 8v4.5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="12" cy="16" r="0.6" fill="currentColor" stroke="none"/>',
    info: '<path d="M12 11v5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><circle cx="12" cy="8" r="0.7" fill="currentColor" stroke="none"/>',
  };
  var CLOSE_SVG =
    '<svg viewBox="0 0 16 16" width="16" height="16" fill="none" aria-hidden="true"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>';

  function ensureToaster(position) {
    position = position || "bottom-right";
    var t = document.querySelector('.jl-toaster[data-pos="' + position + '"]');
    if (!t) {
      t = document.createElement("div");
      t.className = "jl-toaster";
      t.setAttribute("data-pos", position);
      document.body.appendChild(t);
    }
    return t;
  }

  function dismiss(el) {
    if (!el || el.__leaving) return;
    el.__leaving = true;
    el.setAttribute("data-leaving", "true");
    setTimeout(function () {
      if (el.parentNode) el.parentNode.removeChild(el);
    }, 200);
  }

  function show(opts) {
    if (typeof document === "undefined") return null;
    if (typeof opts === "string") opts = { description: opts };
    opts = opts || {};
    var position = opts.position || "bottom-right";
    var toaster = ensureToaster(position);

    var el = document.createElement("div");
    el.className = "jl-toast" + (opts.tone ? " jl-toast--" + opts.tone : "");
    el.setAttribute("role", "status");

    if (opts.tone && ICONS[opts.tone]) {
      var icon = document.createElement("span");
      icon.className = "jl-toast__icon";
      icon.innerHTML =
        '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.6" opacity="0.35"/>' +
        ICONS[opts.tone] +
        "</svg>";
      el.appendChild(icon);
    }

    var body = document.createElement("div");
    body.className = "jl-toast__body";
    if (opts.title) {
      var ti = document.createElement("div");
      ti.className = "jl-toast__title";
      ti.textContent = opts.title;
      body.appendChild(ti);
    }
    if (opts.description) {
      var de = document.createElement("div");
      de.className = "jl-toast__desc";
      de.textContent = opts.description;
      body.appendChild(de);
    }

    var timer;
    function remove() {
      if (timer) clearTimeout(timer);
      dismiss(el);
    }

    if (opts.action && opts.action.label) {
      var ab = document.createElement("button");
      ab.type = "button";
      ab.className = "jl-toast__action";
      ab.textContent = opts.action.label;
      ab.addEventListener("click", function () {
        if (opts.action.onClick) opts.action.onClick();
        remove();
      });
      body.appendChild(ab);
    }
    el.appendChild(body);

    var close = document.createElement("button");
    close.type = "button";
    close.className = "jl-toast__close";
    close.setAttribute("aria-label", "Dismiss");
    close.innerHTML = CLOSE_SVG;
    close.addEventListener("click", remove);
    el.appendChild(close);

    // newest on top for top-* positions
    if (position.indexOf("top") === 0) toaster.insertBefore(el, toaster.firstChild);
    else toaster.appendChild(el);

    if (opts.duration !== Infinity && opts.duration !== 0) {
      timer = setTimeout(remove, opts.duration || 4500);
    }
    return el;
  }

  function toned(tone) {
    return function (description, opts) {
      var o = { tone: tone, description: description };
      if (opts) for (var k in opts) o[k] = opts[k];
      return show(o);
    };
  }

  J.toast = function (opts) {
    return show(opts);
  };
  J.toast.success = toned("success");
  J.toast.warning = toned("warning");
  J.toast.danger = toned("danger");
  J.toast.info = toned("info");
  J.toast.dismiss = function (el) {
    dismiss(el);
  };
})();

/* ---- toggle.js ---- */
/* JLDS behavior — Toggle. A standalone .jl-toggle flips its own aria-pressed;
 * a .jl-toggle-group manages single (default) or data-type="multiple" selection.
 * Emits jl-toggle:change. Requires core.js (or the all.js bundle). */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function val(btn) {
    return btn.dataset.value || btn.textContent.trim();
  }

  function initStandalone(btn) {
    if (btn.__jlToggle || btn.closest(".jl-toggle-group")) return;
    btn.__jlToggle = true;
    btn.addEventListener("click", function () {
      if (btn.disabled) return;
      var on = btn.getAttribute("aria-pressed") === "true";
      btn.setAttribute("aria-pressed", on ? "false" : "true");
      btn.dispatchEvent(
        new CustomEvent("jl-toggle:change", { detail: { pressed: !on }, bubbles: true })
      );
    });
  }

  function initGroup(group) {
    if (group.__jlToggle) return;
    group.__jlToggle = true;
    var multiple = group.dataset.type === "multiple";
    var btns = Array.prototype.slice.call(group.querySelectorAll(".jl-toggle"));

    btns.forEach(function (btn) {
      btn.addEventListener("click", function () {
        if (btn.disabled) return;
        var on = btn.getAttribute("aria-pressed") === "true";
        if (multiple) {
          btn.setAttribute("aria-pressed", on ? "false" : "true");
        } else {
          btns.forEach(function (b) {
            b.setAttribute("aria-pressed", "false");
          });
          if (!on) btn.setAttribute("aria-pressed", "true");
        }
        var value;
        if (multiple) {
          value = btns
            .filter(function (b) { return b.getAttribute("aria-pressed") === "true"; })
            .map(val);
        } else {
          var sel = group.querySelector('.jl-toggle[aria-pressed="true"]');
          value = sel ? val(sel) : null;
        }
        group.dispatchEvent(
          new CustomEvent("jl-toggle:change", { detail: { value: value }, bubbles: true })
        );
      });
    });
  }

  register("toggle", function (root) {
    root.querySelectorAll(".jl-toggle-group").forEach(initGroup);
    root.querySelectorAll(".jl-toggle").forEach(initStandalone);
  });
})();

/* ---- tooltip.js ---- */
/* JLDS behavior — Tooltip. Shows the .jl-tooltip__pop on hover/focus of the
 * .jl-tooltip wrapper (after an optional data-delay). Requires core.js (or all.js).
 * Positioning is pure CSS via the pop's data-side. */
(function () {
  function register(name, fn) {
    var J = (window.JLDS = window.JLDS || {});
    if (J.register) J.register(name, fn);
    else (J._pending = J._pending || []).push([name, fn]);
  }

  function initTooltip(tip) {
    if (tip.__jlTip) return;
    tip.__jlTip = true;
    var pop = tip.querySelector(".jl-tooltip__pop");
    if (!pop) return;
    var delay = parseInt(tip.dataset.delay, 10);
    if (isNaN(delay)) delay = 120;
    var timer;

    function open() {
      timer = setTimeout(function () {
        pop.setAttribute("data-show", "true");
      }, delay);
    }
    function close() {
      clearTimeout(timer);
      pop.removeAttribute("data-show");
    }

    tip.addEventListener("mouseenter", open);
    tip.addEventListener("mouseleave", close);
    tip.addEventListener("focusin", open);
    tip.addEventListener("focusout", close);
  }

  register("tooltip", function (root) {
    root.querySelectorAll(".jl-tooltip").forEach(initTooltip);
  });
})();
